---
title: "Awards"
format: html
---


**2024**

- <b>Excellence in Graduate Teaching</b>, Faculty of Health Sciences, McMaster University, 2024


- <b>Teaching Excellence Award</b>, Department of Health Research Methods, Evidence, and Impact, McMaster University, 2024



**2021**

- <b>Summer Program in Aging Trainee Award</b>, Canadian Institute of Health Research (CIHR), 2021 ($500)



**2020**

- <b>Publication Award</b>, Faculty of Health Sciences, McMaster University, 2020


- <b>Diversity Award</b>, Faculty of Health Sciences, McMaster University, 2020


- <b>Teaching Assistant Excellence Award</b>, Faculty of Health Sciences, McMaster University, 2020


- <b>Excellence in Communication and Collaboration Award</b>, Faculty of Health Sciences, McMaster University, 2020




**2019**

- <b>Ontario Graduate Scholarship (OGS)</b>, 2019 ($15,000)




**2018**

- <b>Young Investigator Award, American Society for Bone and Mineral Research</b>, 2018 (US $1,000)

- <b>Tim Murray Award, Osteoporosis Canada</b>, 2018 ($1,500)


- <b>Ontario Graduate Scholarship (OGS)</b>, 2018 ($15,000)




**2017**

- <b>Drug Safety and Effectiveness Cross-Disciplinary Training (DSECT)Trainee Award</b>, Canadian Institute of Health Research (CIHR), 2017 ($10,000)




**2016**

- <b>Ontario Graduate Scholarship (OGS)</b>, 2016 ($15,000)

